CREATE TABLE [NAM] (
  [maNam] VARCHAR(10) PRIMARY KEY,
  [tenNam] VARCHAR(50) NOT NULL,
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [HOCKY] (
  [maHK] VARCHAR(10) PRIMARY KEY,
  [tenHK] VARCHAR(50) NOT NULL,
  [maNam] VARCHAR(10) NOT NULL,
  [ngayBatDau] DATE NOT NULL,
  [ngayKetThuc] DATE NOT NULL,
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [GIAOVIEN] (
  [maGV] VARCHAR(10) PRIMARY KEY,
  [hoTen] NVARCHAR(100) NOT NULL,
  [ngaySinh] DATE,
  [gioiTinh] NVARCHAR(10),
  [soDienThoai] VARCHAR(15),
  [email] VARCHAR(100),
  [diaChi] NVARCHAR(200),
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [LOP] (
  [maLop] VARCHAR(10) PRIMARY KEY,
  [tenLop] NVARCHAR(50) NOT NULL,
  [siSo] INT DEFAULT (0),
  [maNam] VARCHAR(10) NOT NULL,
  [maGVCN] VARCHAR(10),
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [HOCSINH] (
  [maHS] VARCHAR(10) PRIMARY KEY,
  [hoTen] NVARCHAR(100) NOT NULL,
  [ngaySinh] DATE NOT NULL,
  [gioiTinh] NVARCHAR(10),
  [diaChi] NVARCHAR(200),
  [soDienThoai] VARCHAR(15),
  [email] VARCHAR(100),
  [maLop] VARCHAR(10),
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [PHUHUYNH] (
  [maPH] VARCHAR(10) PRIMARY KEY,
  [hoTen] NVARCHAR(100) NOT NULL,
  [soDienThoai] VARCHAR(15),
  [email] VARCHAR(100),
  [ngheNghiep] NVARCHAR(100),
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [HOCSINH_PHUHUYNH] (
  [maHS] VARCHAR(10),
  [maPH] VARCHAR(10),
  [quanHe] NVARCHAR(50),
  [trangThai] BOOLEAN DEFAULT (TRUE),
  PRIMARY KEY ([maHS], [maPH])
)
GO

CREATE TABLE [MON] (
  [maMon] VARCHAR(10) PRIMARY KEY,
  [tenMon] NVARCHAR(100) NOT NULL,
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [PHANCONG] (
  [maPC] VARCHAR(10) PRIMARY KEY,
  [maGV] VARCHAR(10) NOT NULL,
  [maMon] VARCHAR(10) NOT NULL,
  [maLop] VARCHAR(10) NOT NULL,
  [maNam] VARCHAR(10) NOT NULL,
  [ghiChu] NVARCHAR(200),
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [CHITIETMON] (
  [maChiTiet] VARCHAR(10) PRIMARY KEY,
  [maMon] VARCHAR(10) NOT NULL,
  [tenChiTiet] NVARCHAR(100) NOT NULL,
  [heSo] INT NOT NULL,
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [DIEM] (
  [maDiem] VARCHAR(10) PRIMARY KEY,
  [maHS] VARCHAR(10) NOT NULL,
  [maChiTiet] VARCHAR(10) NOT NULL,
  [maHocKy] VARCHAR(10) NOT NULL,
  [diemThuongXuyen] FLOAT,
  [diemGiuaKy] FLOAT,
  [diemCuoiKy] FLOAT,
  [diemTBMonHocKy] FLOAT
)
GO

CREATE TABLE [HANHKIEM] (
  [maHanhKiem] VARCHAR(10) PRIMARY KEY,
  [maHS] VARCHAR(10) NOT NULL,
  [maHocKy] VARCHAR(10) NOT NULL,
  [xepLoai] NVARCHAR(20),
  [soLanViPham] INT DEFAULT (0),
  [nhanXet] NVARCHAR(500)
)
GO

CREATE TABLE [VIPHAM] (
  [maViPham] VARCHAR(10) PRIMARY KEY,
  [maHS] VARCHAR(10) NOT NULL,
  [maHocKy] VARCHAR(10) NOT NULL,
  [ngayViPham] DATE NOT NULL,
  [noiDung] NVARCHAR(500),
  [mucDo] NVARCHAR(50),
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [XEPLOAI] (
  [maXepLoai] VARCHAR(10) PRIMARY KEY,
  [maHS] VARCHAR(10) NOT NULL,
  [maHocKy] VARCHAR(10) NOT NULL,
  [xepLoaiHocLuc] NVARCHAR(20),
  [xepLoaiHanhKiem] NVARCHAR(20),
  [diemTBChung] FLOAT,
  [nhanXet] NVARCHAR(500),
  [duocLenLop] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [THOIKHOABIEU] (
  [maTKB] VARCHAR(10) PRIMARY KEY,
  [maLop] VARCHAR(10) NOT NULL,
  [maHocKy] VARCHAR(10) NOT NULL,
  [ngayBatDau] DATE,
  [ngayKetThuc] DATE,
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

CREATE TABLE [CHITIETTIET] (
  [maChiTiet] VARCHAR(10) PRIMARY KEY,
  [maTKB] VARCHAR(10) NOT NULL,
  [maMon] VARCHAR(10) NOT NULL,
  [thu] NVARCHAR(20) NOT NULL,
  [tiet] INT NOT NULL,
  [phongHoc] VARCHAR(20),
  [gioBatDau] TIME,
  [gioKetThuc] TIME,
  [trangThai] BOOLEAN DEFAULT (TRUE)
)
GO

ALTER TABLE [HOCKY] ADD FOREIGN KEY ([maNam]) REFERENCES [NAM] ([maNam]) ON DELETE CASCADE
GO

ALTER TABLE [LOP] ADD FOREIGN KEY ([maNam]) REFERENCES [NAM] ([maNam]) ON DELETE CASCADE
GO

ALTER TABLE [LOP] ADD FOREIGN KEY ([maGVCN]) REFERENCES [GIAOVIEN] ([maGV]) ON DELETE SET NULL
GO

ALTER TABLE [HOCSINH] ADD FOREIGN KEY ([maLop]) REFERENCES [LOP] ([maLop]) ON DELETE SET NULL
GO

ALTER TABLE [HOCSINH_PHUHUYNH] ADD FOREIGN KEY ([maHS]) REFERENCES [HOCSINH] ([maHS]) ON DELETE CASCADE
GO

ALTER TABLE [HOCSINH_PHUHUYNH] ADD FOREIGN KEY ([maPH]) REFERENCES [PHUHUYNH] ([maPH]) ON DELETE CASCADE
GO

ALTER TABLE [PHANCONG] ADD FOREIGN KEY ([maGV]) REFERENCES [GIAOVIEN] ([maGV]) ON DELETE CASCADE
GO

ALTER TABLE [PHANCONG] ADD FOREIGN KEY ([maMon]) REFERENCES [MON] ([maMon]) ON DELETE CASCADE
GO

ALTER TABLE [PHANCONG] ADD FOREIGN KEY ([maLop]) REFERENCES [LOP] ([maLop]) ON DELETE CASCADE
GO

ALTER TABLE [PHANCONG] ADD FOREIGN KEY ([maNam]) REFERENCES [NAM] ([maNam]) ON DELETE CASCADE
GO

ALTER TABLE [CHITIETMON] ADD FOREIGN KEY ([maMon]) REFERENCES [MON] ([maMon]) ON DELETE CASCADE
GO

ALTER TABLE [DIEM] ADD FOREIGN KEY ([maHS]) REFERENCES [HOCSINH] ([maHS]) ON DELETE CASCADE
GO

ALTER TABLE [DIEM] ADD FOREIGN KEY ([maChiTiet]) REFERENCES [CHITIETMON] ([maChiTiet]) ON DELETE CASCADE
GO

ALTER TABLE [DIEM] ADD FOREIGN KEY ([maHocKy]) REFERENCES [HOCKY] ([maHK]) ON DELETE CASCADE
GO

ALTER TABLE [HANHKIEM] ADD FOREIGN KEY ([maHS]) REFERENCES [HOCSINH] ([maHS]) ON DELETE CASCADE
GO

ALTER TABLE [HANHKIEM] ADD FOREIGN KEY ([maHocKy]) REFERENCES [HOCKY] ([maHK]) ON DELETE CASCADE
GO

ALTER TABLE [VIPHAM] ADD FOREIGN KEY ([maHS]) REFERENCES [HOCSINH] ([maHS]) ON DELETE CASCADE
GO

ALTER TABLE [VIPHAM] ADD FOREIGN KEY ([maHocKy]) REFERENCES [HOCKY] ([maHK]) ON DELETE CASCADE
GO

ALTER TABLE [XEPLOAI] ADD FOREIGN KEY ([maHS]) REFERENCES [HOCSINH] ([maHS]) ON DELETE CASCADE
GO

ALTER TABLE [XEPLOAI] ADD FOREIGN KEY ([maHocKy]) REFERENCES [HOCKY] ([maHK]) ON DELETE CASCADE
GO

ALTER TABLE [THOIKHOABIEU] ADD FOREIGN KEY ([maLop]) REFERENCES [LOP] ([maLop]) ON DELETE CASCADE
GO

ALTER TABLE [THOIKHOABIEU] ADD FOREIGN KEY ([maHocKy]) REFERENCES [HOCKY] ([maHK]) ON DELETE CASCADE
GO

ALTER TABLE [CHITIETTIET] ADD FOREIGN KEY ([maTKB]) REFERENCES [THOIKHOABIEU] ([maTKB]) ON DELETE CASCADE
GO

ALTER TABLE [CHITIETTIET] ADD FOREIGN KEY ([maMon]) REFERENCES [MON] ([maMon]) ON DELETE CASCADE
GO
